# Day 5
## Pandas

### step 1: import pandas

In [146]:
#step 1: import pandas

import pandas as pd

In [147]:
d={
    'Name':['Alice','Bob','charlie'],
    'Age':[20,33,25],
    'City':['NYC','New Jersy','India']
}
d

{'Name': ['Alice', 'Bob', 'charlie'],
 'Age': [20, 33, 25],
 'City': ['NYC', 'New Jersy', 'India']}

In [148]:
# Method 1 : DataFrame

df=pd.DataFrame(d)
df

      Name  Age       City
0    Alice   20        NYC
1      Bob   33  New Jersy
2  charlie   25      India

In [149]:
#task

array4d=[
    [
        [
            [1,2],[3,4]
        ],
        [
            [5,6],[7,8]
        ]
    ],
    [
        [
            [9,10],[11,12]
        ],
        [
            [13,14],[15,16]
        ]
    ]
]

task_df=pd.DataFrame(array4d[0][0],columns=["col1","col2"])
task_df

   col1  col2
0     1     2
1     3     4

In [150]:
# Renaming Column names of data frame
task_df=task_df.rename(columns={'col1':'num1','col2':'num2'})
task_df

   num1  num2
0     1     2
1     3     4

### Step 3 Load the Dataset from system

In [151]:
df=pd.read_csv("dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45.0,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68.0,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57.0,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57.0,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [152]:
df.head()
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57.0,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56.0,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44.0,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52.0,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57.0,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [153]:
df.tail()
df.tail(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
293,67.0,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44.0,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63.0,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63.0,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59.0,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57.0,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45.0,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68.0,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57.0,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57.0,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [154]:
#random set of values
df.sample() 
df.sample(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
138,57.0,1,0,110,201,0,1,126,1,1.5,1,0,1,1
207,60.0,0,0,150,258,0,0,157,0,2.6,1,2,3,0
268,54.0,1,0,122,286,0,0,116,1,3.2,1,2,2,0
133,41.0,1,1,110,235,0,1,153,0,0.0,2,0,2,1
17,66.0,0,3,150,226,0,1,114,0,2.6,0,0,2,1
97,52.0,1,0,108,233,1,1,147,0,0.1,2,3,3,1
223,56.0,0,0,200,288,1,0,133,1,4.0,0,2,3,0
188,50.0,1,2,140,233,0,1,163,0,0.6,1,1,3,0
197,67.0,1,0,125,254,1,1,163,0,0.2,1,2,3,0
290,61.0,1,0,148,203,0,1,161,0,0.0,2,1,3,0

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       298 non-null    float64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(2), int64(12)
memory usage: 33.3 KB

In [156]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,298.00000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.52349,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,8.98190,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.00000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

### Find Missing Values

In [157]:
df.isnull()
df.isnull().sum()


df.isna()
df.isna().sum()

age         5
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### Find missing vales

In [158]:
df['age'].value_counts()    #counts the frequncy of each age i.e persons with age 67 are 12
df['age'].value_counts().sum()

np.int64(298)

### Number of rows and columns

In [159]:
df.shape

(303, 14)

### Handling Missing Values

In [160]:
df['age'].fillna(0,inplace=True)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_18264\4226583780.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(0,inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37.0,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45.0,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68.0,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57.0,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57.0,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [161]:
df.sort_values(by='age',ascending=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
125,0.0,0,1,118,210,0,1,192,0,0.7,2,0,2,1
103,0.0,1,2,120,240,1,1,194,0,0.8,0,0,3,1
149,0.0,1,2,130,180,0,1,150,0,0.0,2,0,2,1
113,0.0,1,0,110,211,0,1,161,0,0.0,2,0,3,1
139,0.0,1,0,128,263,0,1,105,1,0.2,1,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,71.0,0,2,110,265,1,0,130,0,0.0,2,1,2,1
151,71.0,0,0,112,149,0,1,125,0,1.6,1,0,2,1
129,74.0,0,1,120,269,0,0,121,1,0.2,2,1,2,1
144,76.0,0,2,140,197,0,2,116,0,1.1,1,0,2,1
238,77.0,1,0,125,304,0,0,162,1,0.0,2,3,2,0

In [162]:
df.groupby('sex')
df.groupby('sex')['age'].mean()
df.groupby('sex')[['age','chol']].mean()

           age        chol
sex
0    55.322917  261.302083
1    52.835749  239.289855

In [163]:
df.iloc[0:10,0:3]

    age  sex  cp
0  63.0    1   3
1  37.0    1   2
2  41.0    0   1
3  56.0    1   1
4  57.0    0   0
5  57.0    1   0
6  56.0    0   1
7  44.0    1   1
8  52.0    1   2
9  57.0    1   2

In [164]:
df.loc[0:5,['age','sex','cp']]
df.loc[0:5, df.columns[0:3]]

    age  sex  cp
0  63.0    1   3
1  37.0    1   2
2  41.0    0   1
3  56.0    1   1
4  57.0    0   0
5  57.0    1   0

In [165]:
df.dtypes

age         float64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [166]:
df['oldpeak']=df['oldpeak'].astype('int32')

In [167]:
df['oldpeak'].dtype

dtype('int32')

In [168]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [169]:
df['sex'].unique()
for i in df:
    print(df[i].unique())

[63. 37. 41. 56. 57. 44. 52. 54. 48. 49. 64. 58. 50. 66. 43. 69. 59. 42.
 61. 40. 71. 51. 65. 53. 46. 45. 39. 47. 62. 34. 35. 29. 55. 60. 67. 68.
  0. 74. 76. 70. 38. 77.]
[1 0]
[3 2 1 0]
[145 130 120 140 172 150 110 135 160 105 125 142 155 104 138 128 108 134
 122 115 118 100 124  94 112 102 152 101 132 148 178 129 180 136 126 106
 156 170 146 117 200 165 174 192 144 123 154 114 164]
[233 250 204 236 354 192 294 263 199 168 239 275 266 211 283 219 340 226
 247 234 243 302 212 175 417 197 198 177 273 213 304 232 269 360 308 245
 208 264 321 325 235 257 216 256 231 141 252 201 222 260 182 303 265 309
 186 203 183 220 209 258 227 261 221 205 240 318 298 564 277 214 248 255
 207 223 288 160 394 315 246 244 270 195 196 254 126 313 262 215 193 271
 268 267 210 295 306 178 242 180 228 149 278 253 342 157 286 229 284 224
 206 167 230 335 276 353 225 330 290 172 305 188 282 185 326 274 164 307
 249 341 407 217 174 281 289 322 299 300 293 184 409 259 200 327 237 218
 319 166 311 169 187 176 241 131]
[1 0]
[0 1 2]
[150 187 172 178 163 148 153 173 162 174 160 139 171 144 158 114 151 161
 179 137 157 123 152 168 140 188 125 170 165 142 180 143 182 156 115 149
 146 175 186 185 159 130 190 132 147 154 202 166 164 184 122 169 138 111
 145 194 131 133 155 167 192 121  96 126 105 181 116 108 129 120 112 128
 109 113  99 177 141 136  97 127 103 124  88 195 106  95 117  71 118 134
  90]
[0 1]
[2 3 1 0 4 6 5]
[0 2 1]
[0 2 1 3 4]
[1 2 3 0]
[1 0]

In [170]:
df['cp'].nunique()

4

## Commands

In [171]:
df[(df['age']>20) & (df['age']<60) ]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1,37.0,1,2,130,250,0,1,187,0,3,0,0,2,1
2,41.0,0,1,130,204,0,0,172,0,1,2,0,2,1
3,56.0,1,1,120,236,0,1,178,0,0,2,0,2,1
4,57.0,0,0,120,354,0,1,163,1,0,2,0,2,1
5,57.0,1,0,140,192,0,1,148,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59.0,1,0,164,176,1,0,90,0,1,1,2,1,0
298,57.0,0,0,140,241,0,1,123,1,0,1,0,3,0
299,45.0,1,3,110,264,0,1,132,0,1,1,0,3,0
301,57.0,1,0,130,131,0,1,115,1,1,1,1,3,0
302,57.0,0,1,130,236,0,0,174,0,0,1,1,2,0

In [172]:
# comands
df[df['chol']<200].shape[0]
df[df['chol']>200].shape[0]

252

In [173]:
#create new col as chol_levels to fill in with data of chol levels
df['chol_level']=['low' if x<200 else 'high' for x in df['chol']]
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_level
0,63.0,1,3,145,233,1,0,150,0,2,0,0,1,1,high
1,37.0,1,2,130,250,0,1,187,0,3,0,0,2,1,high
2,41.0,0,1,130,204,0,0,172,0,1,2,0,2,1,high
3,56.0,1,1,120,236,0,1,178,0,0,2,0,2,1,high
4,57.0,0,0,120,354,0,1,163,1,0,2,0,2,1,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0,0,140,241,0,1,123,1,0,1,0,3,0,high
299,45.0,1,3,110,264,0,1,132,0,1,1,0,3,0,high
300,68.0,1,0,144,193,1,1,141,0,3,1,2,3,0,low
301,57.0,1,0,130,131,0,1,115,1,1,1,1,3,0,low
302,57.0,0,1,130,236,0,0,174,0,0,1,1,2,0,high

In [174]:
df['chol_level']=df['chol'].apply(
    lambda x:"High" if x>200 else "Low"
)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_level
0,63.0,1,3,145,233,1,0,150,0,2,0,0,1,1,High
1,37.0,1,2,130,250,0,1,187,0,3,0,0,2,1,High
2,41.0,0,1,130,204,0,0,172,0,1,2,0,2,1,High
3,56.0,1,1,120,236,0,1,178,0,0,2,0,2,1,High
4,57.0,0,0,120,354,0,1,163,1,0,2,0,2,1,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0,0,140,241,0,1,123,1,0,1,0,3,0,High
299,45.0,1,3,110,264,0,1,132,0,1,1,0,3,0,High
300,68.0,1,0,144,193,1,1,141,0,3,1,2,3,0,Low
301,57.0,1,0,130,131,0,1,115,1,1,1,1,3,0,Low
302,57.0,0,1,130,236,0,0,174,0,0,1,1,2,0,High

In [141]:
# copy dataset ino a new variable 
safe_data=df.copy()
safe_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_level
0,63.0,1,3,145,233,1,0,150,0,2,0,0,1,1,High
1,37.0,1,2,130,250,0,1,187,0,3,0,0,2,1,High
2,41.0,0,1,130,204,0,0,172,0,1,2,0,2,1,High
3,56.0,1,1,120,236,0,1,178,0,0,2,0,2,1,High
4,57.0,0,0,120,354,0,1,163,1,0,2,0,2,1,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0,0,140,241,0,1,123,1,0,1,0,3,0,High
299,45.0,1,3,110,264,0,1,132,0,1,1,0,3,0,High
300,68.0,1,0,144,193,1,1,141,0,3,1,2,3,0,Low
301,57.0,1,0,130,131,0,1,115,1,1,1,1,3,0,Low
302,57.0,0,1,130,236,0,0,174,0,0,1,1,2,0,High

In [142]:
# download dataframe in local machine
df.to_csv('safe_dataset.csv',index=False)

In [108]:
# check for duplicates
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [177]:
df.drop_duplicates(inplace=True)

In [178]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target, chol_level]
Index: []

In [182]:
# if you deleted or dropped column index might mismatch so to reset index we use this
df.reset_index(drop=True,inplace=True)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_level
0,63.0,1,3,145,233,1,0,150,0,2,0,0,1,1,High
1,37.0,1,2,130,250,0,1,187,0,3,0,0,2,1,High
2,41.0,0,1,130,204,0,0,172,0,1,2,0,2,1,High
3,56.0,1,1,120,236,0,1,178,0,0,2,0,2,1,High
4,57.0,0,0,120,354,0,1,163,1,0,2,0,2,1,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57.0,0,0,140,241,0,1,123,1,0,1,0,3,0,High
298,45.0,1,3,110,264,0,1,132,0,1,1,0,3,0,High
299,68.0,1,0,144,193,1,1,141,0,3,1,2,3,0,Low
300,57.0,1,0,130,131,0,1,115,1,1,1,1,3,0,Low
301,57.0,0,1,130,236,0,0,174,0,0,1,1,2,0,High

In [ ]:
df['Gender'].replace({"M":"Male","F":"Female"},inplace=True)  ## replace example but do not run as there no such variable