In [10]:
import numpy as np
import pandas as pd
df=pd.read_csv("transactions.csv")
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details
0,06-26-2015,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,05-26-2015,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,06-01-2015,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,06-05-2015,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,12-17-2015,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...
49995,09-18-2015,4005664,53.95,Games,Dice Games,Irving,Texas,credit
49996,10-02-2015,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit
49997,05-03-2015,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash
49998,10-23-2015,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit
49999,12-14-2015,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit

In [12]:
#What is the total sales amount across all transactions?
x=pd.to_numeric(df['t_amt'],errors='coerce').sum()
x

np.float64(5110820.54)

In [48]:
#Which month had the highest total transaction amount?
df['t_date']=pd.to_datetime(df['t_date'],dayfirst=True,errors="coerce")
x=df.groupby(df['t_date'].dt.month)['t_amt'].sum()
x.columns = ['Month', 'TotalTransactionValue']
x

t_date
1     438165.76
2     395262.37
3     444664.24
4     420695.24
5     432627.58
6     421074.55
7     439560.80
8     434255.01
9     429321.63
10    424856.28
11    408846.35
12    421490.73
Name: t_amt, dtype: float64

In [15]:
#What is the average transaction amount per customer?
df.groupby('cust_id')['t_amt'].mean()

cust_id
4000000    127.444000
4000001    108.945556
4000002     56.165000
4000003    123.670000
4000004    168.135000
              ...
4009995     65.018571
4009996    104.515000
4009997    121.547500
4009998    110.950000
4009999     85.252500
Name: t_amt, Length: 9926, dtype: float64

In [57]:
#What is the trend of total sales over months?
#total sales done in each month in terms of total transactions done 
df.groupby(df['t_date'].dt.month)['t_amt'].sum()

t_date
1     438165.76
2     395262.37
3     444664.24
4     420695.24
5     432627.58
6     421074.55
7     439560.80
8     434255.01
9     429321.63
10    424856.28
11    408846.35
12    421490.73
Name: t_amt, dtype: float64

In [58]:
#total sales done in each month in terms of number of customers
df.groupby(df['t_date'].dt.month)['cust_id'].count()

t_date
1     4268
2     3834
3     4360
4     4175
5     4205
6     4171
7     4252
8     4250
9     4160
10    4181
11    3994
12    4150
Name: cust_id, dtype: int64

In [18]:
#What is the highest single transaction amount recorded?
df['t_amt'].max()

200.0

In [24]:
#Which service category contributes the most to total revenue?
df.groupby('services')['t_amt'].sum()

services
Air Sports                 99316.90
Combat Sports             164730.67
Dancing                    42603.71
Exercise & Fitness        766463.87
Games                     374932.70
Gymnastics                327225.34
Indoor Games              288506.04
Jumping                   205842.67
Outdoor Play Equipment    294728.28
Outdoor Recreation        846678.64
Puzzles                    61564.75
Racquet Sports            166976.06
Team Sports               617461.38
Water Sports              531815.97
Winter Sports             321973.56
Name: t_amt, dtype: float64

In [65]:
#Which product generated the highest revenue?
df.groupby('products_used')['t_amt'].sum().idxmax()

'Yoga & Pilates'

In [49]:
#How does the average transaction amount vary between services?
df.groupby('services')['t_amt'].mean()

services
Air Sports                103.455104
Combat Sports             101.061761
Dancing                   102.907512
Exercise & Fitness        103.660247
Games                     102.272968
Gymnastics                102.385901
Indoor Games              103.074684
Jumping                   102.155171
Outdoor Play Equipment    101.281196
Outdoor Recreation        100.999480
Puzzles                   100.595997
Racquet Sports            103.647461
Team Sports               102.738998
Water Sports              101.899975
Winter Sports             101.217718
Name: t_amt, dtype: float64

In [56]:
#How many unique customers made purchases?
df['cust_id'].nunique()

9926

In [63]:
#Which customers have spent the most overall?
df.groupby('cust_id')['t_amt'].sum()

cust_id
4000000    637.22
4000001    980.51
4000002    112.33
4000003    371.01
4000004    672.54
            ...
4009995    455.13
4009996    836.12
4009997    486.19
4009998    665.70
4009999    682.02
Name: t_amt, Length: 9926, dtype: float64

In [66]:
#What is the average number of transactions per customer?
df.groupby('cust_id')['t_amt'].mean()

cust_id
4000000    127.444000
4000001    108.945556
4000002     56.165000
4000003    123.670000
4000004    168.135000
              ...
4009995     65.018571
4009996    104.515000
4009997    121.547500
4009998    110.950000
4009999     85.252500
Name: t_amt, Length: 9926, dtype: float64

In [70]:
#Are there customers who made multiple purchases in different categories?
df.groupby('cust_id')['services'].value_counts()

cust_id  services
4000000  Outdoor Recreation        2
         Games                     1
         Indoor Games              1
         Winter Sports             1
4000001  Racquet Sports            2
                                  ..
4009999  Water Sports              3
         Outdoor Recreation        2
         Outdoor Play Equipment    1
         Racquet Sports            1
         Team Sports               1
Name: count, Length: 39790, dtype: int64

In [78]:
#What percentage of customers are repeat buyers?
x=(df['cust_id'].count())-(df['cust_id'].nunique())
x=(x/(df['cust_id'].count()))*100
x

np.float64(80.148)

In [79]:
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details
0,2015-06-26,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,2015-05-26,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,2015-06-01,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,2015-06-05,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,2015-12-17,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...
49995,2015-09-18,4005664,53.95,Games,Dice Games,Irving,Texas,credit
49996,2015-10-02,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit
49997,2015-05-03,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash
49998,2015-10-23,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit
49999,2015-12-14,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit

In [95]:
#Which product category has the highest total sales?
product=df.groupby('services')['t_amt'].sum().idxmax()
product

'Outdoor Recreation'

In [96]:
#Which services are most popular by transaction count?
df.groupby('services')['t_amt'].count().idxmax()

'Outdoor Recreation'

In [132]:
#For each service, which product type is purchased most frequently?
df.groupby(['services','products_used'])['t_amt'].count()

services       products_used
Air Sports     Air Suits        191
               Hang Gliding     369
               Parachutes       400
Combat Sports  Boxing           431
               Fencing          394
                               ...
Winter Sports  Luge             413
               Sledding         395
               Snowboarding     374
               Snowmobiling     380
               Snowshoeing      409
Name: t_amt, Length: 125, dtype: int64

In [134]:
freq_prod=df.groupby("services")["products_used"].agg(lambda x:x.value_counts().idxmax())
freq_prod

services
Air Sports                                Parachutes
Combat Sports                                 Boxing
Dancing                                  Ballet Bars
Exercise & Fitness        Cardio Machine Accessories
Games                                        Mahjong
Gymnastics                             Balance Beams
Indoor Games                                Foosball
Jumping                                  Trampolines
Outdoor Play Equipment                    Swing Sets
Outdoor Recreation                        Lawn Games
Puzzles                               Jigsaw Puzzles
Racquet Sports                             Badminton
Team Sports                                   Hockey
Water Sports                            Bodyboarding
Winter Sports                   Cross-Country Skiing
Name: products_used, dtype: object

In [110]:
#What is the average transaction amount per product type?
df.groupby('products_used')['t_amt'].mean()

products_used
Abdominal Equipment    105.362798
Air Hockey             103.775478
Air Suits              101.421832
Archery                 97.345564
Badminton              108.441138
                          ...
Wetsuits               102.042775
Whitewater Rafting     102.877744
Windsurfing            104.161453
Wrestling               97.895364
Yoga & Pilates         107.668784
Name: t_amt, Length: 125, dtype: float64

In [114]:
#Are there specific services where customers spend significantly more?
df.groupby('services')['t_amt'].sum().idxmax()

'Outdoor Recreation'

In [135]:
avg_sale=df["t_amt"].mean()
specific_serv=df.loc[df["t_amt"]>avg_sale,"services"]
specific_serv

1        Exercise & Fitness
3                Gymnastics
5        Outdoor Recreation
9                   Jumping
10       Outdoor Recreation
                ...
49992          Water Sports
49994    Outdoor Recreation
49996                 Games
49998            Gymnastics
49999           Team Sports
Name: services, Length: 24899, dtype: object

In [116]:
#Which state has the highest total sales?
df.groupby('state')['t_amt'].sum().idxmax()

'California'

In [119]:
#Which city records the highest number of transactions?
df.groupby('city')['t_amt'].sum().idxmax()

'Pasadena'

In [136]:
#What is the average spending per transaction in each state?
df.groupby('state')['t_amt'].mean()

state
Alabama                 102.487049
Arizona                 102.172241
California              102.652182
Colorado                101.537415
Connecticut              99.982108
District of Columbia    103.800334
Florida                 103.136567
Georgia                 102.330675
Hawaii                  101.536667
Idaho                    98.969538
Illinois                100.166315
Indiana                 100.712664
Iowa                    103.100727
Kansas                  101.436926
Kentucky                104.130392
Louisiana               103.466335
Maryland                100.506913
Massachusetts           104.541571
Michigan                101.547777
Minnesota               103.465157
Mississippi             101.214926
Missouri                100.969040
Nebraska                101.955690
Nevada                  105.434718
New Jersey              103.438005
New York                100.259452
North Carolina          103.033172
Ohio                    101.350817
Oklahoma                104.995771
Oregon                  102.438143
Pennsylvania            102.776034
South Carolina          103.540065
Tennessee                99.265804
Texas                   101.379891
Utah                    104.507560
Virginia                104.976206
Washington              101.401603
Wisconsin               101.953159
Name: t_amt, dtype: float64

In [163]:
#Are certain services more popular in specific states?
df.groupby(['services','state'])['t_amt'].sum()

services       state
Air Sports     Alabama         2389.44
               Arizona         2362.28
               California     11840.84
               Colorado        4095.68
               Connecticut     2065.41
                                ...
Winter Sports  Texas          35623.64
               Utah            5223.27
               Virginia        7189.75
               Washington     12496.24
               Wisconsin       7073.17
Name: t_amt, Length: 570, dtype: float64

In [162]:
df.groupby('state')['services'].agg(lambda x: x.value_counts().idxmax())

state
Alabama                 Outdoor Recreation
Arizona                 Outdoor Recreation
California              Outdoor Recreation
Colorado                Outdoor Recreation
Connecticut             Outdoor Recreation
District of Columbia    Exercise & Fitness
Florida                 Outdoor Recreation
Georgia                 Outdoor Recreation
Hawaii                  Outdoor Recreation
Idaho                   Outdoor Recreation
Illinois                Outdoor Recreation
Indiana                 Outdoor Recreation
Iowa                    Outdoor Recreation
Kansas                  Outdoor Recreation
Kentucky                Outdoor Recreation
Louisiana               Outdoor Recreation
Maryland                Outdoor Recreation
Massachusetts           Outdoor Recreation
Michigan                Outdoor Recreation
Minnesota               Outdoor Recreation
Mississippi             Outdoor Recreation
Missouri                Outdoor Recreation
Nebraska                Outdoor Recreation
Nevada                  Exercise & Fitness
New Jersey              Outdoor Recreation
New York                Exercise & Fitness
North Carolina          Outdoor Recreation
Ohio                    Outdoor Recreation
Oklahoma                Outdoor Recreation
Oregon                  Outdoor Recreation
Pennsylvania            Outdoor Recreation
South Carolina          Outdoor Recreation
Tennessee               Outdoor Recreation
Texas                   Outdoor Recreation
Utah                    Exercise & Fitness
Virginia                Exercise & Fitness
Washington              Exercise & Fitness
Wisconsin               Outdoor Recreation
Name: services, dtype: object

In [146]:
#Which states buy the most Outdoor Recreation products?
x=df.loc[df['services']=='Outdoor Recreation']
x.groupby('state')['t_amt'].sum()

state
Alabama                  18197.03
Arizona                  24426.25
California              120605.09
Colorado                 27605.07
Connecticut              14592.22
District of Columbia      7046.35
Florida                  47959.38
Georgia                  15912.77
Hawaii                    7513.52
Idaho                     7885.45
Illinois                 22933.09
Indiana                   9677.66
Iowa                      7765.27
Kansas                   15869.04
Kentucky                 16532.71
Louisiana                 8480.19
Maryland                  8085.69
Massachusetts            26458.03
Michigan                 13883.05
Minnesota                17928.51
Mississippi               8201.95
Missouri                 22301.50
Nebraska                 14962.41
Nevada                   14427.91
New Jersey               22091.40
New York                 14393.36
North Carolina           14530.52
Ohio                     30917.35
Oklahoma                  6483.88
Oregon                   32892.83
Pennsylvania             15271.72
South Carolina           16050.35
Tennessee                31080.93
Texas                    81616.93
Utah                     14178.02
Virginia                 18931.03
Washington               29612.15
Wisconsin                19378.03
Name: t_amt, dtype: float64

In [177]:
#Compare average spending between California and Texas customers.
cal=df.loc[(df["state"]=="California")].groupby('state')['t_amt'].sum()
tex=df.loc[(df["state"]=="Texas")].groupby('state')['t_amt'].sum()
avg=(float(cal)+float(tex))/2
avg

C:\Users\DELL\AppData\Local\Temp\ipykernel_18356\902342390.py:3: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  avg=(float(cal)+float(tex))/2

621806.735

In [179]:
avg = df.loc[df["state"].isin(["California","Texas"])].groupby("state")["t_amt"].sum().mean()
avg

np.float64(621806.735)